### PR TITLE
Feature/linyan geometry

### PR DESCRIPTION
**Pull request by linyan-w**
Update Geometry wrt DocDB 1662

### CODE REVIEW

**Comment by linyan-w** [comment]
Hi Paul,

Thanks for the review. 
It seems the merge is still blocked. I think you need to tick the "approve the merge" option when submitting the review.

Best,
Linyan

**Review by paullglebrun — COMMENTED** [review]
O.K.

**Comment by paullglebrun** [comment]
Where do I find the approve request silly button?

**Comment by linyan-w** [comment]
https://docs.gitlab.com/ee/user/project/merge_requests/reviews/#submit-a-review
There is some instruction here

**Comment by paullglebrun** [comment]
O.K.,

**Pull request merged**
