### PR TITLE
Grid Submission for EMPHATIC

### PR DESCRIPTION
**Pull request by aolivier23**
I created a new directory and two new scripts to submit EMPHATIC jobs to the grid: GridSubmission/submitGenerator.sh and GridSubmission/submitReconstruction.sh.  submitGenerator.sh requires a configuration generator script name that does search and replace on input .fcl files.  GridSubmission includes an example configuration generator script that changes the run number and random seed (for GEANT only!) in a special input .fcl file based on g4gen_job.fcl.

This branch is ready for an early production campaign on the grid.  I have tested submitGenerator.sh and both operating modes of submitReconstruction.sh over a few 10s of jobs.

There are a few features I purposely left out to get us ready to run on the grid sooner:
- Random seeds for other modules that are different for each grid job
- More detailed input validation in submitGenerator.sh and submitReconstruction.sh.  Right now, they just make sure we're writing output to /pnfs and not overwriting on /pnfs.
- Submitting directly from the SL7 container.  The grid jobs run under SL7, but the submission scripts have to be run from AL9 for now because Fermilab's AL9 container template doesn't seem to have jobsub.
- Instructions because I plan to write a wiki page instead of a README.  The submission scripts do print some usage information when they see -h or --help on the command line.
- Any knowledge of run databases or file metadata.  Choosing things like the right geometry for the run number seems to come from ART modules in emphaticsoft.  I left enough flexibility in the configuration generator for submitGenerator.sh to hopefully let us retrofit any file metadata handling we need one day.

### CODE REVIEW

**Review by gavinsdavies — COMMENTED** [review]
ooooh this is exciting! Nice work, @aolivier23 !! 
So, for ease of version control and more rapid development of grid related tools, I actually made [emphprod](https://github.com/EMPHATICSoft/emphprod) repository to collect scripts. we can version it outside of the main software stack. 
i'd like to discuss simply moving your new directory to be under the emphprod umbrella / structure. thoughts?
other pieces look fine to me.

**Comment by aolivier23** [comment]
@gavinsdavies Can do.  Should I close this pull request and open a new one in emphprod?

The only downside is that my grid submission code figures out what tarball to ship based on where the grid submission scripts are called from.  So, emphprod has to be sitting next to emphaticsoft in the directory tree.  I'm already shipping the directory above emphaticsoft (before moving to emphprod; will become directory above emphprod), so I think this will be transparent?

**Comment by aolivier23** [comment]
Oh, and I think I added a few lines to some of our setup scripts to make them work on the grid.  I had to do some backflips to make a setup script work portably.  So we need linked pull requests here and in emphprod.  DUNE does that, so it shouldn't be a problem for us.

**Comment by aolivier23** [comment]
I'll give it half a day to try this afternoon or tomorrow depending on when the GPVMs come back up.  I'm optimistic that moving the scripts to emphprod won't be too big a deal.  If I'm still stuck at the end of that time, let's consider this pull request to get a starting point out to the collaboration.

**Comment by gavinsdavies** [comment]
cool. we can tag a version of emphprod and drop on cvmfs for your testing , so it doesn't need shipping with grid jobs-- they should be able to see cvmfs

**Comment by aolivier23** [comment]
Done and tested!  See https://github.com/EMPHATICSoft/emphprod/pull/6  I think this pull request should pick up my latest change to the branch that moves most of my grid submission scripts from here to emphprod.

**Review by gavinsdavies — APPROVED** [review]
Awesome. Thanks, Andrew!

**Pull request merged**
